name: Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            benchmark_command: ./benchmarkbin/CircularBuffer_Fixed_Benchmark
          - os: ubuntu-latest
            benchmark_command: ./benchmarkbin/CircularBuffer_Dynamic_Benchmark
          - os: macos-latest
            benchmark_command: ./benchmarkbin/CircularBuffer_Fixed_Benchmark
          - os: macos-latest
            benchmark_command: ./benchmarkbin/CircularBuffer_Dynamic_Benchmark
          - os: windows-latest
            benchmark_command: .\benchmarkbin\CircularBuffer_Fixed_Benchmark.exe
          - os: windows-latest
            benchmark_command: .\benchmarkbin\CircularBuffer_Dynamic_Benchmark.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v3.21.1
      with:
        cmakeVersion: '3.18.4'

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Run Fixed Benchmark
      if: ${{ contains(matrix.benchmark_command, 'Fixed') }}
      run: ${{ matrix.benchmark_command }} > fixed_benchmark_result.txt

    - name: Run Dynamic Benchmark
      if: ${{ contains(matrix.benchmark_command, 'Dynamic') }}
      run: ${{ matrix.benchmark_command }} > dynamic_benchmark_result.txt

    - name: Upload Fixed Benchmark Results
      if: ${{ contains(matrix.benchmark_command, 'Fixed') }}
      uses: actions/upload-artifact@v2
      with:
        name: fixed-benchmark-results
        path: fixed_benchmark_result.txt

    - name: Upload Dynamic Benchmark Results
      if: ${{ contains(matrix.benchmark_command, 'Dynamic') }}
      uses: actions/upload-artifact@v2
      with:
        name: dynamic-benchmark-results
        path: dynamic_benchmark_result.txt