name: Formal Verification

on:
  push:
  pull_request:

jobs:
  verify:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        set -eux
        sudo apt-get update
        sudo apt-get install -y \
          cmake ninja-build \
          clang-16 clang++-16 llvm-16-dev libclang-common-16-dev libclang-cpp16-dev \
          valgrind \
          z3 libz3-dev \
          cvc4 libcvc4-dev \
          cvc5 libcvc5-dev \
          minisat \
          libcryptominisat5-dev \
          autoconf automake libtool pkg-config libgmp-dev
          # libpicosat-dev

    - name: Build Btor2Tools from source
      run: |
        set -eux
        git clone https://github.com/Boolector/btor2tools.git /tmp/btor2tools-src
        pushd /tmp/btor2tools-src
          mkdir build && cd build
          cmake .. \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja
          ninja -j$(nproc)
          sudo ninja install
        popd

    - name: Build Boolector from source
      run: |
        set -eux
        git clone https://github.com/Boolector/boolector.git /tmp/boolector-src
        pushd /tmp/boolector-src
          mkdir build && cd build
          cmake .. \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja
          ninja -j$(nproc)
          sudo ninja install
        popd

    - name: Build Yices from source
      run: |
        set -eux
        # clone & bootstrap
        git clone https://github.com/SRI-CSL/yices2.git /tmp/yices2-src
        pushd /tmp/yices2-src

          # generate the configure script
          autoconf

          # configure & build
          ./configure \
            --prefix=/usr/local \
            --enable-shared \
            --disable-static \
            --enable-thread-safe
          make -j$(nproc)

          # install into /usr/local
          sudo make install

        popd

    - name: Check tool versions
      run: |
        clang++-16 --version
        ninja --version
        valgrind --version
        esbmc --version

    - name: Configure CMake (verification only)
      run: cmake -S . -B build \
        -DCMAKE_C_COMPILER=clang-16 \
        -DCMAKE_CXX_COMPILER=clang++-16 \
        -DBUILD_CIRCULARBUFFER_VERIFICATION=ON \
        -DDOWNLOAD_DEPENDENCIES=OFF \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -G Ninja

    - name: Build & Run `verify` target
      run: cmake --build build --target verify -- -j$(nproc)

    - name: Upload verification logs
      uses: actions/upload-artifact@v4
      with:
        name: formal-results
        path: build/formal_results/
