name: Ubuntu X86_64

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev libtbb-dev cmake

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v3.21.1

    - name: Check GCC Version
      run: g++ --version

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build -DBUILD_CIRCULARBUFFER_MULTI_THREADING=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Test with Retry
      working-directory: build
      run: |
        set +e  # Disable exit on error
        max_retries=10
        attempt=1
        while [ $attempt -le $max_retries ]; do
          echo "Test attempt $attempt"
          ctest --output-on-failure -C Release
          test_result=$?
          if [ $test_result -eq 0 ]; then
            echo "Tests passed on attempt $attempt"
            exit 0
          else
            echo "Tests failed on attempt $attempt"
          fi
          attempt=$((attempt + 1))
          sleep 1
        done
        echo "All $max_retries attempts failed"
        exit 1

    - name: Run Fixed Benchmarks
      run: ./build/benchmarkbin/CircularBuffer_Fixed_Benchmark > fixed_benchmark_results.txt
  
    - name: Run Dynamic Benchmarks
      run: ./build/benchmarkbin/CircularBuffer_Dynamic_Benchmark > dynamic_benchmark_results.txt

    - name: Upload Fixed Benchmark results
      uses: actions/upload-artifact@v2
      with:
        name: dynamic_benchmark_results
        path: fixed_benchmark_results.txt

    - name: Upload Dynamic Benchmark results
      uses: actions/upload-artifact@v2
      with:
        name: dynamic-benchmark-results
        path: fixed_benchmark_results.txt