name: Ubuntu X86_64

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev libtbb-dev cmake

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v3.21.1

    - name: Check GCC Version
      run: g++ --version

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build -DBUILD_CIRCULARBUFFER_MULTI_THREADING=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Test with Retry
      run: |
        max_retries=10
        attempt=1
        while [ $attempt -le $max_retries ]; do
          echo "Test attempt $attempt"
          ctest --output-on-failure -C Release
          if [ $? -eq 0 ]; then
            echo "Tests passed on attempt $attempt"
            break
          else
            echo "Tests failed on attempt $attempt"
          fi
          attempt=$((attempt + 1))
        done
        if [ $attempt -gt $max_retries ]; then
          echo "All $max_retries attempts failed"
          exit 1
        fi
      working-directory: build