name: Ubuntu X86_64

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev libtbb-dev cmake

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v3.21.1

    - name: Check GCC Version
      run: g++ --version

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -S . -B build -DBUILD_CIRCULARBUFFER_MULTI_THREADING=ON -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Test with Retry
      working-directory: build
      run: |
        set +e  # Disable exit on error
        max_retries=10
        attempt=1
        while [ $attempt -le $max_retries ]; do
          echo "Test attempt $attempt"
          ctest --output-on-failure -C Release
          test_result=$?
          if [ $test_result -eq 0 ]; then
            echo "Tests passed on attempt $attempt"
            exit 0
          else
            echo "Tests failed on attempt $attempt"
          fi
          attempt=$((attempt + 1))
          sleep 1
        done
        echo "All $max_retries attempts failed"
        exit 1

    - name: Run Fixed Benchmarks
      run: ./build/benchmarkbin/CircularBuffer_Fixed_Benchmark | tee fixed_benchmark_results.txt
  
    - name: Run Dynamic Benchmarks
      run: ./build/benchmarkbin/CircularBuffer_Dynamic_Benchmark | tee dynamic_benchmark_results.txt

    - name: Display Fixed Benchmark results
      run: cat fixed_benchmark_results.txt

    - name: Display Dynamic Benchmark results
      run: cat dynamic_benchmark_results.txt

    - name: Create Benchmark Results Summary
      run: |
        echo "# Benchmark Results" > benchmark_results.md
        echo "## Fixed Benchmark Results" >> benchmark_results.md
        cat fixed_benchmark_results.txt >> benchmark_results.md
        echo "## Dynamic Benchmark Results" >> benchmark_results.md
        cat dynamic_benchmark_results.txt >> benchmark_results.md
      shell: bash

    - name: Display Benchmark Results Summary
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const path = './benchmark_results.md';
          const content = fs.readFileSync(path, 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: content
          });