name: Windows ARM

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [arm]

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v3.21.1

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Intel TBB for ARM
      run: |
        Invoke-WebRequest -Uri "https://github.com/oneapi-src/oneTBB/releases/download/v2021.7.0/oneapi-tbb-2021.7.0-win.zip" -OutFile "tbb.zip"
        Expand-Archive -Path "tbb.zip" -DestinationPath "tbb"
        echo "TBB_ROOT=$(pwd)/tbb" >> $GITHUB_ENV
        echo "TBB_LIB_DIR=$(pwd)/tbb/oneapi-tbb-2021.7.0/lib/intel64/vc14" >> $GITHUB_ENV
        echo "TBB_INCLUDE_DIR=$(pwd)/tbb/oneapi-tbb-2021.7.0/include" >> $GITHUB_ENV

    - name: Check MSVC Version
      run: |
        try {
          $versionOutput = cl 2>&1
          $match = $versionOutput | Select-String -Pattern "Version (\d+\.\d+)"
          
          if ($match) {
              $version = [Version]$match.Matches.Groups[1].Value
              Write-Output "MSVC version found: $version"

              # Check if version is less than 19.28
              if ($version -lt [Version]"19.28") {
                  throw "MSVC version is less than 19.28"
              }
          } else {
              Write-Output "MSVC version could not be determined. Skipping version check."
              echo "::set-output name=skip_step::true"
          }
        } catch {
          throw $_
        }
      shell: pwsh
      id: check_msvc

    - name: Create build directory
      if: steps.check_msvc.outputs.skip_step != 'true'
      run: mkdir build

    - name: Configure CMake
      if: steps.check_msvc.outputs.skip_step != 'true'
      run: |
        cmake -S . -B build -DBUILD_CIRCULARBUFFER_MULTI_THREADING=ON -DCMAKE_BUILD_TYPE=Release -DTBB_ROOT="$env:TBB_ROOT" -DTBB_LIB_DIR="$env:TBB_LIB_DIR" -DTBB_INCLUDE_DIR="$env:TBB_INCLUDE_DIR"

    - name: List build directory contents
      run: ls -R build/
      
    - name: Build
      run: cmake --build build --config Release --verbose

    - name: Test
      working-directory: build
      run: ctest --output-on-failure -C Release